CREATE TABLE IF NOT EXISTS `years` (
`id` INT UNSIGNED KEY PRIMARY KEY AUTO_INCREMENT,
`name` VARCHAR(15) NOT NULL,
`gpa` DOUBLE NOT NULL,
`student_id` INT UNSIGNED NOT NULL,
FOREIGN KEY (`student_id`) REFERENCES `students`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;